New branch
GoncharukAD/test-guru pull request #2
Opened 2022-07-11 15:33 UTC by GoncharukAD

Добавил таймзону,добавил описания.
Возникли вопросы по указанию версии проекта.Файл versions создал

2022-07-12 06:12 UTC, VidgarVii requested changes

2022-07-12 06:12 UTC, VidgarVii commented on README.md
> +__5. Ответ <br/>
не хватает Категории

2022-07-12 06:12 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
надо разобраться, что делает эта настройка прежде чем её активировать.
В ТЗ речь шла только про локаль по умолчанию

2022-07-12 06:12 UTC, VidgarVii commented on public/about/author.html
> +  <a href="https://github.com/GoncharukAD">github</a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2022-07-12 06:12 UTC, VidgarVii commented on public/about/project.html
> +<html lang="ru">
данная страница должна открываться по адресу /about

2022-07-12 06:12 UTC, VidgarVii commented on config/initializers/versions.rb
> +#Разобраться,как добавить версию проекта сюда
вот [посмотри](https://github.com/plataformatec/devise/blob/master/lib/devise/version.rb) как гем `Devise` хранит свою версию - это стандартный вариант для руби-гемов

а вот [пост](https://alexpeattie.com/blog/defining-versions-in-ruby-gems) про версификацию руби-гемов
посмотри на пример кода с патчем, где идет проверка версии `Devise`
удобно обращаться не просто ко вселенной - `VERSION`, а к конкретному модулю - `Devise::VERSION`
если вдруг код будет подразумевать необходимость использования версий нескольких модулей, то без неймспейсинга совсем не ясно, как разруливать ситуацию

аналогично нужно реализовать и здесь
только модуль конечно не `Devise` будет, а имя твоего приложения (посмотри для примера в файл `config/application.rb`, где ты добавляешь локаль и таймзон, там эти строки конфигурации помещены внутрь модуля твоего приложения)

2022-07-13 15:01 UTC, GoncharukAD commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
Это настройка пути загрузки переводов,вот здесь вычитал http://rusrails.ru/i18n#lenivyy-poisk.
Но т.к. я не понимаю,как это работает,то просто установлю  язык приложения на ru

2022-07-13 15:17 UTC, GoncharukAD commented on config/initializers/versions.rb
> +#Разобраться,как добавить версию проекта сюда
Не нашёл,где находится пример кода с патчем,где идёт проверка версии.
Можете подсказать директорию?

2022-07-13 15:18 UTC, closed without merging